name: unused_code_cleaner
description: "Automatically find and safely remove unused assets, functions, packages, and files from Flutter/Dart projects. Reduce bundle size and improve performance with one command."
version: 1.9.0
topics:
  - flutter
  - optimization
  - cleanup
  - assets
  - performance
homepage: https://github.com/Navid-Rahman/unused_code_cleaner
repository: https://github.com/Navid-Rahman/unused_code_cleaner
issue_tracker: https://github.com/Navid-Rahman/unused_code_cleaner/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  analyzer: ">=6.11.0 <8.1.1"
  args: ^2.7.0
  cli_util: ^0.4.2
  colorize: ^3.0.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.26.3
  lints: ^4.0.0

executables:
  unused_code_cleaner: unused_code_cleaner
