name: unused_code_cleaner
description: "A comprehensive Dart package to identify and remove unused assets, functions, packages, and files with detailed colored logging."
version: 1.0.0
homepage: https://github.com/Navid-Rahman/unused_code_cleaner

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3
  analyzer: ^7.5.6
  args: ^2.7.0
  cli_util: ^0.4.2
  colorize: ^3.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  unused_code_cleaner: unused_code_cleaner
