# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Main package testing (pure Dart)
  test-dart-package:
    runs-on: ubuntu-latest
    name: Test Dart Package

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies for main package
        run: |
          # Temporarily rename example to avoid dependency resolution conflicts
          mv example example_temp || true
          dart pub get
          mv example_temp example || true

      - name: Verify formatting
        run: |
          mv example example_temp || true
          dart format --output=none --set-exit-if-changed .
          mv example_temp example || true

      - name: Analyze project source
        run: |
          mv example example_temp || true
          dart analyze
          mv example_temp example || true

      - name: Run tests
        run: |
          mv example example_temp || true
          dart test
          mv example_temp example || true

      - name: Test CLI tool activation
        run: |
          mv example example_temp || true
          dart pub global activate --source path .
          dart pub global run unused_code_cleaner --help
          mv example_temp example || true

  # Example app testing (requires Flutter)
  test-flutter-example:
    runs-on: ubuntu-latest
    name: Test Flutter Example

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Install dependencies for Flutter example
        working-directory: example
        run: flutter pub get

      - name: Analyze Flutter example
        working-directory: example
        run: flutter analyze
